services:
  api_php:
    build:
      context: ./budgetTrackerApi
      dockerfile: Dockerfile
    container_name: budget_api_php
    volumes:
      - ./budgetTrackerApi:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - db

  api_nginx:
    image: nginx:1.27-alpine
    container_name: budget_api_nginx
    ports:
      - "8080:80"
    volumes:
      - ./budgetTrackerApi:/var/www/html
      - ./budgetTrackerApi/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api_php

  db:
    image: postgres:16-alpine
    container_name: budget_api_db
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budget
    ports:
      - "5432:5432"
    volumes:
      - budget_pgdata:/var/lib/postgresql/data

volumes:
  budget_pgdata: